

#                           $$\                                                   $$\                                   $$\       $$\           
#                           $$ |                                                  $$ |                                  $$ |      \__|          
#        $$$$$$$\  $$$$$$\  $$ | $$$$$$\   $$$$$$\   $$$$$$$\          $$$$$$$\ $$$$$$\    $$$$$$\   $$$$$$\   $$$$$$$\ $$$$$$$\  $$\  $$$$$$\  
#       $$  _____|$$  __$$\ $$ |$$  __$$\ $$  __$$\ $$  _____|$$$$$$\ $$  _____|\_$$  _|   \____$$\ $$  __$$\ $$  _____|$$  __$$\ $$ |$$  __$$\ 
#       $$ /      $$ /  $$ |$$ |$$ /  $$ |$$ |  \__|\$$$$$$\  \______|\$$$$$$\    $$ |     $$$$$$$ |$$ |  \__|\$$$$$$\  $$ |  $$ |$$ |$$ /  $$ |
#       $$ |      $$ |  $$ |$$ |$$ |  $$ |$$ |       \____$$\          \____$$\   $$ |$$\ $$  __$$ |$$ |       \____$$\ $$ |  $$ |$$ |$$ |  $$ |
#       \$$$$$$$\ \$$$$$$  |$$ |\$$$$$$  |$$ |      $$$$$$$  |        $$$$$$$  |  \$$$$  |\$$$$$$$ |$$ |      $$$$$$$  |$$ |  $$ |$$ |$$$$$$$  |
#        \_______| \______/ \__| \______/ \__|      \_______/         \_______/    \____/  \_______|\__|      \_______/ \__|  \__|\__|$$  ____/ 
#                                                                                                                                     $$ |      
#                                                                                                                                     $$ |      
#                                                                                                                                     \__|      
#
#       by Eblanyrt (2025)
#

format = """
[░▒▓](#5A966B)\
[ ❄ ](bg:#5A966B fg:#090c0c)\
[](bg:#BB986E fg:#5A966B)\
$directory\
[](fg:#BB986E bg:#4C70BA)\
$git_branch\
$git_status\
[](fg:#4C70BA bg:#847E93)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#847E93 bg:#6A94B3)\
$time\
[ ](fg:#6A94B3)\
\n$character"""

[directory]
style = "fg:#1a1310 bg:#BB986E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#4C70BA"
format = '[[ $symbol $branch ](fg:#1a1310 bg:#4C70BA)]($style)'

[git_status]
style = "bg:#4C70BA"
format = '[[($all_status$ahead_behind )](fg:#1a1310 bg:#4C70BA)]($style)'

[nodejs]
symbol = ""
style = "bg:#847E93"
format = '[[ $symbol ($version) ](fg:#1a1310 bg:#847E93)]($style)'

[rust]
symbol = ""
style = "bg:#847E93"
format = '[[ $symbol ($version) ](fg:#1a1310 bg:#847E93)]($style)'

[golang]
symbol = ""
style = "bg:#847E93"
format = '[[ $symbol ($version) ](fg:#1a1310 bg:#847E93)]($style)'

[php]
symbol = ""
style = "bg:#847E93"
format = '[[ $symbol ($version) ](fg:#1a1310 bg:#847E93)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6A94B3"
format = '[[  $time ](fg:#1a1310 bg:#6A94B3)]($style)'
